arteria-delivery: update to 2.4.1 for fixing arteria/arteria-core missmatch
WARNING: Generating metadata for package arteria-core produced metadata
for project name arteria. Fix your #egg=arteria-core fragments.
ERROR: Requested arteria from
git+https://github.com/arteria-project/arteria-core.git@v1.0.1#egg=arteria-core
(from -r
/lupus/ngi/irma3/devel-root/stelo_ansible-2.9/sw//arteria/delivery_src/requirements/prod
(line 6)) has different name in metadata: 'arteria'